nodeLinker: node-modules

packageExtensions:
  jest-runner@*:
    peerDependencies:
      jest-environment-jsdom: 23.4.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
