name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  # version that would be tagged as latest
  LATEST_VERSION: 14.21.3

jobs:
  build:
    strategy:
      matrix:
        version: [14.21.3, 16.20.0, 18.16.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          outputs: type=docker
          tags: ${{ matrix.version == env.LATEST_VERSION && format('alfabankui/arui-scripts:{0},alfabankui/arui-scripts:latest', matrix.version) || format('alfabankui/arui-scripts:{0}', matrix.version) }}
          build-args: |
            NODE_VERSION=${{ matrix.version }}
            ALPINE_VERSION=3.16
          context: ./packages/alpine-node-nginx
