name: Create new library package

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'NPM channel to use'
        required: true
        default: 'next'
  push:
    branches:
      - master

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      WORK_SPACE: ${{ github.workspace }}
      NPM_CHANNEL: ${{ github.event.inputs.channel }}
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: create new arui-scripts version
        run: |
          yarn --immutable
          yarn build
          yarn workspace arui-scripts run semantic-release
      - name: create @alfalab/scripts-modules version
        working-directory: ./packages/arui-scripts-modules
        run: |
          npm version --git-tag-version=false $(node -p "require('../arui-scripts/package.json').version")
          npm publish --tag $NPM_CHANNEL
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: create @alfalab/scripts-server version
        working-directory: ./packages/arui-scripts-server
        run: |
          npm version --git-tag-version=false $(node -p "require('../arui-scripts/package.json').version")
          npm publish --tag $NPM_CHANNEL
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
